version: "3.4"

services:
  nginx:
    image: nginx:1.18
    ports:
      - "8080:80"
    volumes:
      - ./data:/usr/share/nginx/html
  go:
    image: golang:1.14
    links:
      - nginx
    environment:
      NGINX_HOST: "nginx"
    volumes:
      - ./:/app
